"""Immutable, strictly validated DTOs for code-quality evaluation."""

from __future__ import annotations

from enum import StrEnum

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    HttpUrl,
    field_validator,
    model_validator,
)


class EvaluationStatus(StrEnum):
    """Represent the outcome status produced by an evaluation layer.

    Members:
        PASS: The evaluation completed successfully.
        FAIL: The evaluation found one or more failing requirements.
        BLOCKED: The evaluation could not proceed because a prerequisite was unavailable.
        ERROR: The evaluation failed because of an unexpected execution error.
        DISAGREE: Evaluation layers reached conflicting outcomes.
    """

    PASS = "pass"
    FAIL = "fail"
    BLOCKED = "blocked"
    ERROR = "error"
    DISAGREE = "disagree"


class ResultCategory(StrEnum):
    """Classify a requirement by the evaluation layer that owns it.

    Members:
        DETERMINISTIC: A requirement checked by deterministic tooling.
        SEMANTIC: A requirement assessed by a semantic evaluator.
        AGGREGATE: A requirement derived from multiple evaluation layers.
    """

    DETERMINISTIC = "deterministic"
    SEMANTIC = "semantic"
    AGGREGATE = "aggregate"


class Language(StrEnum):
    """Identify source languages supported by the evaluator.

    Members:
        PYTHON: Python source code.
        JAVASCRIPT: JavaScript source code.
        TYPESCRIPT: TypeScript source code.
        MARKDOWN: Markdown documentation.
        JSON: JSON data.
        POWERSHELL: PowerShell scripts.
    """

    PYTHON = "python"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    MARKDOWN = "markdown"
    JSON = "json"
    POWERSHELL = "powershell"


def _stable(value: str) -> str:
    """Validate and return a stable identifier.

    Args:
        value: Candidate identifier.

    Returns:
        str: The unchanged identifier when valid.

    Raises:
        ValueError: If the identifier is empty, too long, or contains unsafe characters.
    """

    if not value:
        raise ValueError("invalid stable identifier")

    exceeds_length_limit = len(value) > 128
    normalized_value = value.replace("-", "").replace("_", "")
    contains_only_alphanumeric = normalized_value.isalnum()

    if exceeds_length_limit or not contains_only_alphanumeric:
        raise ValueError("invalid stable identifier")

    return value


def _path(value: str) -> str:
    """Validate and return a safe relative POSIX path.

    Args:
        value: Candidate relative path.

    Returns:
        str: The unchanged path when valid.

    Raises:
        ValueError: If the path is absolute, traverses parents, or contains unsafe separators.
    """

    if not value:
        raise ValueError("unsafe relative path")

    is_absolute = value.startswith(("/", "\\"))
    contains_drive_separator = ":" in value
    contains_parent_segment = ".." in value.split("/")
    contains_windows_separator = "\\" in value
    contains_duplicate_separator = "//" in value

    if (
        is_absolute
        or contains_drive_separator
        or contains_parent_segment
        or contains_windows_separator
        or contains_duplicate_separator
    ):
        raise ValueError("unsafe relative path")

    return value


def _model_name(value: str) -> str:
    """Validate and return a provider model identifier.

    Args:
        value: Candidate model name.

    Returns:
        str: The unchanged model name when valid.

    Raises:
        ValueError: If the name is empty, too long, or contains unsupported characters.
    """

    if not value:
        raise ValueError("invalid model identifier")

    allowed_punctuation = {"-", "_", ".", "/", ":"}
    has_invalid_character = any(
        not character.isalnum() and character not in allowed_punctuation
        for character in value
    )
    exceeds_length_limit = len(value) > 256
    starts_with_alphanumeric = value[0].isalnum()

    if exceeds_length_limit or not starts_with_alphanumeric or has_invalid_character:
        raise ValueError("invalid model identifier")

    return value


class DTO(BaseModel):
    """Provide immutable, strict, extra-forbidden behavior for all DTOs."""

    model_config = ConfigDict(frozen=True, extra="forbid", strict=True)

    @classmethod
    def json_schema(cls) -> dict[str, object]:
        """Return the generated JSON schema for this DTO class.

        Args:
            No arguments are accepted.

        Returns:
            dict[str, object]: JSON-schema mapping generated by Pydantic.
        """

        return cls.model_json_schema()


class ModelSpec(DTO):
    """Describe one unresolved model provider configuration.

    Attributes:
        model: Provider model identifier.
        base_url: HTTPS provider endpoint.
        api_key: Environment-variable credential reference.
        temperature: Sampling temperature.
        max_tokens: Maximum generated token count.
        enabled: Whether this model may run."""

    model: str
    base_url: HttpUrl
    api_key: str = Field(pattern=r"^\$[A-Za-z_][A-Za-z0-9_]*$")
    temperature: float = Field(0.0, ge=0, le=2)
    max_tokens: int = Field(2048, gt=0, le=1000000)
    enabled: bool = True

    @field_validator("model")
    @classmethod
    def valid_model(cls, value: str) -> str:
        """Validate the configured model identifier.

        Args:
            value: Candidate provider model identifier.

        Returns:
            str: The unchanged identifier when it satisfies the provider syntax.

        Raises:
            ValueError: If the identifier is empty, too long, or contains unsupported characters.
        """

        return _model_name(value)

    @field_validator("base_url")
    @classmethod
    def require_https(cls, value: HttpUrl) -> HttpUrl:
        """Require model provider URLs to use HTTPS.

        Args:
            value: Parsed provider endpoint.

        Returns:
            HttpUrl: The unchanged HTTPS endpoint.

        Raises:
            ValueError: If the endpoint uses a non-HTTPS scheme.
        """

        if value.scheme != "https":
            raise ValueError("base_url must use HTTPS")

        return value


class RetrySpec(DTO):
    """Configure bounded retry attempts and backoff limits.

    Attributes:
        max_attempts: Maximum attempts including the initial call.
        backoff_seconds: Delay between retries."""

    max_attempts: int = Field(1, ge=1, le=10)
    backoff_seconds: float = Field(0, ge=0, le=3600)


class CommandSpec(DTO):
    """Describe one executable command and execution limits.

    Attributes:
        id: Stable command identifier.
        argv: Immutable executable argument vector.
        expected_exit_code: Successful process exit code.
        timeout: Maximum execution duration in seconds.
        retry: Retry policy for failed executions."""

    id: str
    argv: tuple[str, ...]
    expected_exit_code: int = 0
    timeout: float = Field(60, gt=0, le=86400)
    retry: RetrySpec = RetrySpec()
    _id = field_validator("id")(_stable)

    @field_validator("argv")
    @classmethod
    def valid_argv(cls, v: tuple[str, ...]) -> tuple[str, ...]:
        """Require a non-empty argument vector without NUL bytes.

        Args:
            v: Immutable command argument vector.

        Returns:
            tuple[str, ...]: The validated argument vector.

        Raises:
            ValueError: If no arguments are supplied or an argument contains NUL.
        """

        if not v:
            raise ValueError("argv must be non-empty")

        has_invalid_argument = any(not argument or "\x00" in argument for argument in v)

        if has_invalid_argument:
            raise ValueError("argv must be non-empty")

        return v


class InMemoryFile(DTO):
    """Represent one source artifact held in memory.

    Attributes:
        path: Safe relative POSIX artifact path.
        language: Source language.
        content: Complete source text."""

    path: str
    language: Language
    content: str
    _path = field_validator("path")(_path)


class RequirementSpec(DTO):
    """Declare one evaluator requirement and category.

    Attributes:
        id: Stable requirement identifier.
        description: Human-readable requirement text.
        category: Owning evaluation layer.
        required_gate_ids: Referenced gate identifiers."""

    id: str
    description: str
    category: ResultCategory
    required_gate_ids: tuple[str, ...] = ()
    _id = field_validator("id")(_stable)


class ArtifactCheckSpec(DTO):
    """Describe an optional artifact validation gate.

    Attributes:
        id: Stable gate identifier.
        description: Human-readable gate description.
        command: Optional validation command."""

    id: str
    description: str
    command: CommandSpec | None = None
    _id = field_validator("id")(_stable)


class FormatterSpec(DTO):
    """Describe a formatter command for one language.

    Attributes:
        id: Stable formatter identifier.
        language: Language handled by formatter.
        command: Formatting command."""

    id: str
    language: Language
    command: CommandSpec
    _id = field_validator("id")(_stable)


class FileEvaluationRequest(DTO):
    """Bundle source files and all deterministic evaluation inputs.

    Attributes:
        files: Immutable source artifacts to evaluate.
        requirements: Requirement declarations associated with the request.
        commands: Explicit commands to execute as deterministic gates.
        artifact_checks: Optional artifact validation gate declarations.
        formatter_checks: Optional formatter command declarations.
        evaluator_id: Optional evaluator profile override.
        baseline_paths: Relative paths identifying baseline artifacts.
        baseline_digests: Digests corresponding to baseline_paths.
    """

    files: tuple[InMemoryFile, ...]
    requirements: tuple[RequirementSpec, ...] = ()
    commands: tuple[CommandSpec, ...] = ()
    artifact_checks: tuple[ArtifactCheckSpec, ...] = ()
    formatter_checks: tuple[FormatterSpec, ...] = ()
    evaluator_id: str | None = None
    baseline_paths: tuple[str, ...] = ()
    baseline_digests: tuple[str, ...] = ()

    @field_validator("files")
    @classmethod
    def require_files(
        cls,
        files: tuple[InMemoryFile, ...],
    ) -> tuple[InMemoryFile, ...]:
        """Require at least one in-memory source artifact.

        Args:
            files: Immutable source artifacts supplied by the caller.

        Returns:
            tuple[InMemoryFile, ...]: Validated non-empty artifact tuple.

        Raises:
            ValueError: No source artifact was supplied.
        """

        if not files:
            raise ValueError("at least one file is required")

        return files

    @field_validator("baseline_paths")
    @classmethod
    def safe_paths(cls, v: tuple[str, ...]) -> tuple[str, ...]:
        """Validate every baseline path as a safe relative path.

        Args:
            v: Immutable baseline path tuple.

        Returns:
            tuple[str, ...]: Validated baseline paths.

        Raises:
            ValueError: If any baseline path is absolute, traverses a parent, or
                contains unsafe separators.
        """

        return tuple(_path(path) for path in v)

    @model_validator(mode="after")
    def validate_references(self) -> FileEvaluationRequest:
        """Validate identifier uniqueness and cross-field references.

        Args:
            No arguments are accepted.

        Returns:
            FileEvaluationRequest: This validated immutable request.

        Raises:
            ValueError: If identifiers, baseline pairs, or gate references are invalid.
        """
        collections = (
            tuple(item.path for item in self.files),
            tuple(item.id for item in self.requirements),
            tuple(item.id for item in self.commands),
            tuple(item.id for item in self.artifact_checks),
            tuple(item.id for item in self.formatter_checks),
        )
        has_duplicate_values = any(
            len(set(values)) != len(values) for values in collections
        )

        if has_duplicate_values:
            raise ValueError("duplicate request identifiers")

        has_mismatched_baselines = len(self.baseline_paths) != len(
            self.baseline_digests
        )

        if has_mismatched_baselines:
            raise ValueError("baseline paths and digests must have matching lengths")

        baseline_pairs = set(zip(self.baseline_paths, self.baseline_digests))
        has_duplicate_baseline_pairs = len(baseline_pairs) != len(self.baseline_paths)

        if has_duplicate_baseline_pairs:
            raise ValueError("baseline path and digest pairs must be unique")

        declared_ids = (
            {item.id for item in self.requirements}
            | {item.id for item in self.commands}
            | {item.id for item in self.artifact_checks}
        )
        has_unknown_gate_reference = any(
            set(item.required_gate_ids) - declared_ids for item in self.requirements
        )

        if has_unknown_gate_reference:
            raise ValueError("required gate IDs must reference declared IDs")

        return self


class Evidence(DTO):
    """Capture source evidence supporting an evaluation result.

    Attributes:
        path: Safe relative evidence path.
        line_start: Optional first relevant line.
        line_end: Optional last relevant line.
        kind: Evidence classification.
        digest: Optional SHA-256 evidence digest.
        summary: Human-readable evidence summary."""

    path: str
    line_start: int | None = Field(None, ge=1)
    line_end: int | None = Field(None, ge=1)
    kind: str
    digest: str | None = Field(None, pattern=r"^[0-9a-f]{64}$")
    summary: str = ""
    _path = field_validator("path")(_path)

    @model_validator(mode="after")
    def validate_line_range(self) -> Evidence:
        """Ensure an evidence line range is ordered when both bounds exist.

        Args:
            No arguments are accepted.

        Returns:
            Evidence: This validated immutable evidence record.

        Raises:
            ValueError: If the ending line precedes the starting line.
        """

        line_start = self.line_start
        line_end = self.line_end
        line_order_is_invalid = (
            line_start is not None and line_end is not None and line_end < line_start
        )

        if line_order_is_invalid:
            raise ValueError("line_end cannot precede line_start")

        return self


class CommandResult(DTO):
    """Record one command execution outcome and redacted evidence.

    Attributes:
        command_id: Stable identifier of the executed command.
        status: Outcome status reported by execution.
        exit_code: Process exit code, when a process started.
        stdout_length: Number of bytes in captured standard output.
        stdout_digest: Optional digest of captured standard output.
        stderr_length: Number of bytes in captured standard error.
        stderr_digest: Optional digest of captured standard error.
        evidence: Immutable evidence records supporting the outcome.
    """

    command_id: str
    status: EvaluationStatus
    exit_code: int | None = None
    stdout_length: int = Field(0, ge=0)
    stdout_digest: str | None = Field(None, pattern=r"^[0-9a-f]{64}$")
    stderr_length: int = Field(0, ge=0)
    stderr_digest: str | None = Field(None, pattern=r"^[0-9a-f]{64}$")
    evidence: tuple[Evidence, ...] = ()
    _id = field_validator("command_id")(_stable)


class GateResult(DTO):
    """Record one deterministic gate outcome and its supporting evidence.

    Attributes:
        gate_id: Stable identifier of the evaluation gate.
        status: Outcome status reported by the gate.
        message: Redacted human-readable gate explanation.
        evidence: Immutable evidence records supporting the outcome.
    """

    gate_id: str
    status: EvaluationStatus
    message: str
    evidence: tuple[Evidence, ...] = ()
    _id = field_validator("gate_id")(_stable)


class DeterministicResult(DTO):
    """Aggregate deterministic command and gate outcomes.

    Attributes:
        status: Overall deterministic-layer status.
        commands: Immutable command execution outcomes in evaluation order.
        gates: Immutable gate outcomes in evaluation order.
    """

    status: EvaluationStatus
    commands: tuple[CommandResult, ...] = ()
    gates: tuple[GateResult, ...] = ()


class SemanticCriterionResult(DTO):
    """Record one semantic rubric criterion result.

    Attributes:
        criterion_id: Stable identifier of the evaluated criterion.
        status: Outcome status assigned to the criterion.
        score: Optional normalized criterion score from zero to one.
        rationale: Redacted explanation for the criterion outcome.
        evidence: Immutable evidence records supporting the outcome.
    """

    criterion_id: str
    status: EvaluationStatus
    score: float | None = Field(None, ge=0, le=1)
    rationale: str = ""
    evidence: tuple[Evidence, ...] = ()
    _id = field_validator("criterion_id")(_stable)


class SemanticResult(DTO):
    """Aggregate semantic criterion outcomes from one evaluator.

    Attributes:
        status: Overall semantic-layer status.
        evaluator_id: Stable identifier of the evaluator profile.
        criteria: Immutable criterion outcomes in evaluator order.
        blocks_aggregate: Whether this result prevents an aggregate PASS.
    """

    status: EvaluationStatus
    evaluator_id: str
    criteria: tuple[SemanticCriterionResult, ...] = ()
    blocks_aggregate: bool = False
    _id = field_validator("evaluator_id")(_stable)


class AggregateResult(DTO):
    """Combine deterministic and optional semantic evaluation layers.

    Attributes:
        status: Final aggregate outcome status.
        deterministic: Required deterministic-layer result.
        semantic: Optional semantic-layer result.
        message: Redacted human-readable aggregate explanation.
    """

    status: EvaluationStatus
    deterministic: DeterministicResult
    semantic: SemanticResult | None = None
    message: str = ""

    @model_validator(mode="after")
    def valid(self) -> AggregateResult:
        """Ensure PASS is only reported when every required layer passes.

        Args:
            No arguments are accepted.

        Returns:
            AggregateResult: This validated immutable aggregate.

        Raises:
            ValueError: If a passing aggregate contains a non-passing required layer.
        """

        deterministic_failed = self.deterministic.status is not EvaluationStatus.PASS
        semantic_blocks_aggregate = (
            self.semantic is not None and self.semantic.blocks_aggregate
        )

        if self.status is EvaluationStatus.PASS and (
            deterministic_failed or semantic_blocks_aggregate
        ):
            raise ValueError("PASS requires all required layers to pass")

        return self


class SemanticPolicy(DTO):
    """Configure optional LLM evaluation without resolving credentials.

    Attributes:
        enabled: Whether semantic evaluation may run.
        required: Whether a semantic non-pass prevents aggregate success.
        models: Ordered model fallbacks using unresolved environment references.
        retry: Bounded retry policy for transport failures.
        timeout_seconds: Maximum duration of one provider request.
    """

    enabled: bool = True
    required: bool = False
    models: tuple[ModelSpec, ...] = ()
    retry: RetrySpec = RetrySpec()
    timeout_seconds: float = Field(30, gt=0, le=600)

    @model_validator(mode="after")
    def require_enabled_model(self) -> SemanticPolicy:
        """Require at least one model when semantic evaluation is enabled.

        Args:
            No arguments are accepted.

        Returns:
            SemanticPolicy: Validated immutable semantic policy.

        Raises:
            ValueError: Semantic evaluation is enabled without a model.
        """

        if self.enabled and not self.models:
            raise ValueError("enabled semantic policy requires a model")

        return self


class DocumentationPolicy(DTO):
    """Define documentation requirements for one source language.

    Attributes:
        require_module: Whether a module-level docstring is required.
        require_classes: Whether class docstrings are required.
        require_callables: Whether callable docstrings are required.
        include_private: Whether private declarations are included.
        include_nested: Whether nested declarations are included.
        require_constructor: Whether constructor documentation is required.
        require_exact_args: Whether callable argument sections must be exact.
        require_returns: Whether return sections are required.
        require_raises_for_explicit_raise: Whether explicit raises require documentation.
        require_dataclass_attributes: Whether dataclass attributes must be documented.
        required_sections: Required documentation section identifiers.
    """

    require_module: bool = False
    require_classes: bool = False
    require_callables: bool = False
    include_private: bool = False
    include_nested: bool = False
    require_constructor: bool = False
    require_exact_args: bool = False
    require_returns: bool = False
    require_raises_for_explicit_raise: bool = False
    require_dataclass_attributes: bool = False
    required_sections: tuple[str, ...] = ()

    @field_validator("required_sections")
    @classmethod
    def unique_sections(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Require unique, stable documentation section identifiers.

        Args:
            value: Immutable section identifier tuple.

        Returns:
            tuple[str, ...]: Validated stable section identifiers.

        Raises:
            ValueError: If the tuple contains duplicate identifiers or an identifier
                fails stable-identifier validation.
        """

        if len(set(value)) != len(value):
            raise ValueError("required sections must be unique")

        return tuple(_stable(item) for item in value)


class VerticalLayoutPolicy(DTO):
    """Define vertical spacing rules for one source language.

    Attributes:
        enabled: Whether vertical spacing checks are enabled.
        blank_before: Syntax tokens requiring preceding blank lines.
        blank_after: Syntax tokens requiring following blank lines.
        minimum_blank_lines: Minimum number of blank lines required.
    """

    enabled: bool
    blank_before: tuple[str, ...] = ()
    blank_after: tuple[str, ...] = ()
    minimum_blank_lines: int = Field(1, ge=1, le=3)

    @field_validator("blank_before", "blank_after")
    @classmethod
    def unique_tokens(cls, value: tuple[str, ...]) -> tuple[str, ...]:
        """Require unique, stable vertical-layout token identifiers.

        Args:
            value: Immutable layout token tuple.

        Returns:
            tuple[str, ...]: Validated stable layout token identifiers.

        Raises:
            ValueError: If the tuple contains duplicate identifiers or an identifier
                fails stable-identifier validation.
        """

        if len(set(value)) != len(value):
            raise ValueError("layout tokens must be unique")

        return tuple(_stable(item) for item in value)


class CompactnessPolicy(DTO):
    """Define compactness and one-line statement restrictions.

    Attributes:
        forbid_semicolons: Whether semicolon-separated statements are forbidden.
        forbid_one_line_suites: Whether one-line suites are forbidden.
        max_statements_per_line: Maximum statements allowed on one line.
        max_operations_per_statement: Optional operation-count limit per statement.
        exempt_comprehensions: Whether comprehensions bypass operation limits.
        exempt_fluent_chains: Whether fluent chains bypass operation limits.
    """

    forbid_semicolons: bool
    forbid_one_line_suites: bool
    max_statements_per_line: int = Field(1, ge=1, le=10)
    max_operations_per_statement: int | None = Field(None, ge=1, le=100)
    exempt_comprehensions: bool
    exempt_fluent_chains: bool


class OccurrencePolicy(DTO):
    """Define evidence collection behavior for policy gates.

    Attributes:
        collect_all: Whether every matching occurrence must be collected.
        max_evidence_per_gate: Maximum evidence records retained per gate.
        require_fixed_gate_set: Whether the evaluator requires a fixed gate set.
    """

    collect_all: bool
    max_evidence_per_gate: int = Field(100, ge=1, le=10000)
    require_fixed_gate_set: bool


class LanguageQualityPolicy(DTO):
    """Describe complete deterministic and semantic quality rules for one language.

    Attributes:
        language: Language governed by this quality policy.
        line_length: Maximum line length, or None to disable the gate.
        documentation: Documentation requirements for the language.
        vertical_layout: Blank-line and vertical-layout requirements.
        compactness: Statement compactness and one-line restrictions.
        occurrences: Evidence collection and fixed-gate requirements.
        required_literals: Literal values required in selected artifacts.
        forbidden_literals: Literal values forbidden in selected artifacts.
        forbidden_patterns: Regular expressions forbidden in selected artifacts.
        formatters: Formatter gate specifications for the language.
        semantic_requirements: Semantic rubric requirements.
        semantic_threshold: Minimum mean semantic score for a passing result.
        semantic_policy: Model, retry, timeout, and required-layer settings.
        required_gate_ids: Gate identifiers required by this policy.
    """

    language: Language
    line_length: int | None = Field(None, ge=40, le=500)
    documentation: DocumentationPolicy
    vertical_layout: VerticalLayoutPolicy
    compactness: CompactnessPolicy
    occurrences: OccurrencePolicy
    required_literals: tuple[str, ...] = ()
    forbidden_literals: tuple[str, ...] = ()
    forbidden_patterns: tuple[str, ...] = ()
    formatters: tuple[FormatterSpec, ...] = ()
    semantic_requirements: tuple[RequirementSpec, ...] = ()
    semantic_threshold: float = Field(0.8, ge=0, le=1)
    semantic_policy: SemanticPolicy
    required_gate_ids: tuple[str, ...] = ()

    @model_validator(mode="after")
    def validate_policy(self) -> LanguageQualityPolicy:
        """Validate identifiers, references, language alignment, and categories.

        Args:
            No arguments are accepted.

        Returns:
            LanguageQualityPolicy: The validated immutable policy.

        Raises:
            ValueError: If policy collections or references are invalid.
        """

        collections = (
            self.required_literals,
            self.forbidden_literals,
            self.forbidden_patterns,
            tuple(item.id for item in self.formatters),
            tuple(item.id for item in self.semantic_requirements),
            self.required_gate_ids,
        )
        has_duplicate_values = any(
            len(set(items)) != len(items) for items in collections
        )

        if has_duplicate_values:
            raise ValueError("policy identifiers and collections must be unique")

        has_mismatched_formatter_language = any(
            item.language is not self.language for item in self.formatters
        )

        if has_mismatched_formatter_language:
            raise ValueError("formatter language must match policy language")

        has_nonsemantic_requirement = any(
            item.category is not ResultCategory.SEMANTIC
            for item in self.semantic_requirements
        )

        if has_nonsemantic_requirement:
            raise ValueError("semantic requirements must be semantic")

        return self


class EvaluatorSpec(DTO):
    """Configure deterministic and semantic evaluation for one profile.

    Attributes:
        id: Stable evaluator profile identifier.
        languages: Languages accepted by this evaluator.
        path_patterns: Logical path patterns selected at the caller boundary.
        language_policies: Exactly one quality policy per declared language.
    """

    id: str
    languages: tuple[Language, ...]
    path_patterns: tuple[str, ...] = ("**/*",)
    language_policies: tuple[LanguageQualityPolicy, ...]
    _id = field_validator("id")(_stable)

    def policy_for(self, language: Language) -> LanguageQualityPolicy:
        """Return the exact policy for a declared language.

        Args:
            language: Declared language to resolve.

        Returns:
            LanguageQualityPolicy: Matching immutable policy.

        Raises:
            ValueError: If no exact policy exists for the language.
        """

        for policy in self.language_policies:
            if policy.language is language:
                return policy

        raise ValueError("language has no quality policy")

    @model_validator(mode="after")
    def validate_profile(self) -> EvaluatorSpec:
        """Validate uniqueness and semantic-category consistency.

        Args:
            No arguments are accepted.

        Returns:
            EvaluatorSpec: Validated immutable evaluator profile.

        Raises:
            ValueError: Languages are duplicated, language policies do not exactly
                cover the evaluator languages, or a policy does not collect all
                evidence with fixed gates.
        """

        policy_languages = tuple(item.language for item in self.language_policies)
        language_count = len(self.languages)
        unique_language_count = len(set(self.languages))
        has_no_languages = language_count == 0
        has_duplicate_languages = unique_language_count != language_count

        if has_no_languages or has_duplicate_languages:
            raise ValueError("evaluator languages must be unique")

        has_duplicate_policy_languages = len(set(policy_languages)) != len(
            policy_languages
        )
        covers_exact_languages = set(policy_languages) == set(self.languages)

        if has_duplicate_policy_languages or not covers_exact_languages:
            raise ValueError("language policies must exactly cover evaluator languages")

        has_noncollecting_policy = any(
            not policy.occurrences.collect_all
            or not policy.occurrences.require_fixed_gate_set
            for policy in self.language_policies
        )

        if has_noncollecting_policy:
            raise ValueError(
                "production policies must collect all evidence with fixed gates"
            )

        return self


class CodeEvaluatorConfig(DTO):
    """Represent the complete isolated utility configuration.

    Attributes:
        default_evaluator_id: Profile selected when a request omits evaluator_id.
        evaluators: Immutable evaluator profiles.
    """

    default_evaluator_id: str
    evaluators: tuple[EvaluatorSpec, ...]
    _default_id = field_validator("default_evaluator_id")(_stable)

    @model_validator(mode="after")
    def validate_evaluators(self) -> CodeEvaluatorConfig:
        """Require unique profiles and a resolvable default profile.

        Args:
            No arguments are accepted.

        Returns:
            CodeEvaluatorConfig: Validated immutable configuration.

        Raises:
            ValueError: Profiles are empty, duplicated, or omit the default.
        """

        evaluator_ids = tuple(item.id for item in self.evaluators)

        if not evaluator_ids:
            raise ValueError("at least one evaluator is required")

        if len(set(evaluator_ids)) != len(evaluator_ids):
            raise ValueError("evaluator IDs must be unique")

        if self.default_evaluator_id not in evaluator_ids:
            raise ValueError("default evaluator is not configured")

        return self
